server:
  port: 8085

spring:
  application:
    name: auth-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0