# while running app locally
#spring.datasource.url=jdbc:mysql://localhost:3307/cartdb?useSSL=false&allowPublicKeyRetrieval=true
# while running inside container
spring.datasource.url=jdbc:mysql://mysql-cart:3306/cartdb?useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=user
spring.datasource.password=user123
server.port=8082

# JPA settings (optional for auto-creation)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect

# Eureka service discovery
spring.application.name=cart-service
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}